# in _config.yml
title: Curso Python
author: Alejandro Acosta León
year: 2021
logo: images/python-logo.png

bibtex_bibfiles:
    - /home/alejo/OneDrive/References/python-course.bib

execute:
  execute_notebooks: "auto"

# Information about where the book exists on the web
repository:
  url                       : https://github.com/alejo-acosta/python-course
  # path_to_book              : _build/html/
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"